---
name: publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: 5 1 * * 5 # Every Friday at 1:05 AM GMT
jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Docker container registry.
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | \
          docker login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Build the Docker image.
        run: docker build --tag ghcr.io/${{ github.repository }}:latest .
      - name: Publish the Docker image.
        run: docker push ghcr.io/${{ github.repository }}:latest
